package izmac

import (
	"math"
	"time"

	"github.com/ivanizag/izmac/component"
)

/*
The timing of the whole machine falls out of a single counter. The video is
generated by discrete logic with no frame buffer of its own, so the processor
and the screen run from the same clock: 352 cycles make a scan line, 370 scan
lines make a frame of which 342 are visible.

That gives the 60.15Hz vertical blanking the system runs on, and a sound
sample rate of one byte per scan line, 22254Hz, without emulating anything
cycle by cycle.
*/
const (
	// CPUClockMhz is the clock of the Macintosh Plus
	CPUClockMhz = 7.8336

	cyclesPerLine = 352
	linesPerFrame = 370
	visibleLines  = 342

	// cyclesPerSecond drives the seconds counter of the clock and the one
	// second interrupt
	cyclesPerSecond = uint64(CPUClockMhz * 1_000_000)

	// vBlankLine is where the vertical blanking starts
	vBlankLine = visibleLines
)

const (
	maxWaitDuration = 100 * time.Millisecond

	/*
		cyclesPerSpin is how much the run loop gets through between looking
		at the command channel and at the clock. A scan line of cycles is
		a fixed amount of emulated time whatever instructions happen to
		fall in it, which counting instructions instead is not: a hundred
		MOVEQs and a hundred DIVUs are the same number and an order of
		magnitude apart in time, so the sleep the loop works out from them
		would be as far out.
	*/
	cyclesPerSpin = cyclesPerLine
)

// Run starts the emulation
func (m *Mac) Run() {
	m.reset()
	m.paused.Store(false)

	referenceTime := time.Now()
	speedReferenceTime := referenceTime
	speedReferenceCycles := uint64(0)

	for {
		if !m.paused.Load() {
			target := m.cycles + cyclesPerSpin
			for m.cycles < target {
				m.step()
			}
		} else {
			time.Sleep(200 * time.Millisecond)
		}

		if m.executeCommands() {
			return
		}

		if cycleDuration := m.pacedCycleDuration(); cycleDuration != 0 {
			/*
				Wait until the next step has to run. A zero duration is the
				full speed option, nothing is thrown away then.

				A machine coming out of full speed, which a click does for
				as long as it takes to catch the second one, arrives here
				with a reference time from long before and simulated cycles
				that ran nowhere near the clock. It is the same case as
				falling behind, and the resynchronization below puts the
				reference where the cycles say it should be.
			*/
			clockDuration := time.Since(referenceTime)
			simulatedDuration := time.Duration(float64(m.cycles) * cycleDuration)
			waitDuration := simulatedDuration - clockDuration
			if waitDuration > maxWaitDuration || -waitDuration > maxWaitDuration {
				// Too far ahead or too far behind, resynchronize
				referenceTime = referenceTime.Add(-waitDuration)
				waitDuration = 0
			}
			if waitDuration > 0 {
				time.Sleep(waitDuration)
			}
		}

		if m.cycles-speedReferenceCycles > 1000000 {
			newTime := time.Now()
			elapsedCycles := float64(m.cycles - speedReferenceCycles)
			m.currentFreqMHz.Store(math.Float64bits(
				1000.0 * elapsedCycles / float64(newTime.Sub(speedReferenceTime).Nanoseconds())))
			speedReferenceTime = newTime
			speedReferenceCycles = m.cycles
		}
	}
}

/*
RunFrames runs the emulation for a number of frames as fast as it can,
stopping early if the machine halts while the sadmac tracer is on. It is what
the headless frontend and the tests use.

Calling it again carries on from where the last call left off rather than
starting the machine over, so a caller can boot, do something, and run on to
see what came of it. Only the first call, or one after Reset(), starts the
machine.
*/
func (m *Mac) RunFrames(frames uint64) {
	if !m.started {
		m.reset()
	}

	target := m.frames + frames
	for m.frames < target {
		m.step()
		if m.sadMacTrace && m.halt.halted {
			return
		}
	}
}

// step runs one instruction and everything hanging from it
func (m *Mac) step() {
	pc := m.cpu.GetPC()

	if m.toolboxTrace {
		m.traceToolboxAt(pc)
	}
	if m.sadMacTrace {
		m.halt.inspect(pc, m.registerFingerprint(), m.cycles)
	}

	startCycles := m.cpu.GetCycles()
	m.cpu.ExecuteInstruction()
	m.tick(m.cpu.GetCycles() - startCycles)
}

// tick advances the machine the cycles the last instruction took, running
// the scan line logic as the line boundaries are crossed
func (m *Mac) tick(cycles uint64) {
	m.cycles += cycles
	m.lineCycles += cycles

	m.via.tick(cycles)

	m.secondCycles += cycles
	if m.secondCycles >= cyclesPerSecond {
		m.secondCycles -= cyclesPerSecond
		m.tickSecond()
	}

	for m.lineCycles >= cyclesPerLine {
		m.lineCycles -= cyclesPerLine
		m.lineTick()
	}

	// After the scan lines, so that a vertical blanking raised on this
	// instruction reaches the processor on the next one and not later
	m.updateInterrupts()
}

// updateInterrupts drives the interrupt request lines of the processor. The
// VIA is on the level 1, the SCC will be on the level 2 and the programmer's
// switch on the level 7.
func (m *Mac) updateInterrupts() {
	level := uint8(0)
	if m.via.interruptAsserted() {
		level = 1
	}
	if m.scc.InterruptAsserted() {
		level = 2
	}
	m.cpu.SetIRQ(level)
}

// lineTick runs once per scan line. It is where the sound samples are
// consumed and where the vertical blanking interrupt is raised.
func (m *Mac) lineTick() {
	m.line++
	if m.line >= linesPerFrame {
		m.line = 0
		m.frames++
	}

	// The sound takes one word of its buffer for every scan line, drawn or
	// not, which is what makes the rate come out at 22254 a second
	m.sound.tick(m.line)

	// One rising edge as the blanking starts and one falling edge as the
	// next frame does, 60.15 times a second
	m.via.setVBlank(m.line >= vBlankLine)

	/*
		The mouse is paid out a quadrature step at a time, the interrupt
		lines to the SCC and the quadrature ones to the VIA. An axis is
		held still while its interrupt is unanswered: the ROM reads the
		quadrature when it services the interrupt, so moving on before
		then changes the level under the edge it is reading.
	*/
	x1, x2, y1, y2 := m.mouse.tick(
		!m.scc.Pending(component.ChannelA), !m.scc.Pending(component.ChannelB))

	// The interrupt lines arrive on the carrier detect inputs, which are
	// active low, so the edge the ROM reads as positive is the falling one
	// of the signal the mouse sends
	m.scc.SetDcd(component.ChannelA, !x1)
	m.scc.SetDcd(component.ChannelB, !y1)
	m.via.setMouseQuadrature(x2, y2)
}

/*
tickSecond advances the clock and pulses the line it interrupts on. A pulse
rather than a toggle so that whichever edge the peripheral control register
selects happens once a second and not once every two.
*/
func (m *Mac) tickSecond() {
	m.rtc.TickSecond()
	m.via.setOneSecond(false)
	m.via.setOneSecond(true)
}

// Reset starts the machine over, as the programmer's switch does
func (m *Mac) Reset() {
	m.reset()
}

func (m *Mac) reset() {
	m.started = true
	m.via.reset()
	m.scc.Reset()
	m.mouse.reset()
	m.keyboard.reset()
	m.mm.setOverlay(true)
	m.halt.reset()
	m.cpu.Reset()

	// The cycles the reset exception itself takes are not counted, the
	// scan line tick starts with the first instruction
	m.cycles = 0
	m.lineCycles = 0
	m.secondCycles = 0
	m.line = 0
}
